<a href="https://colab.research.google.com/github/davicn/CalculoNumerico-Python/blob/master/factoring_methods.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Métodos de Fatoração

## Eliminição Gaussiana 

In [43]:
import numpy as np

def eg(M):
	n = len(M)
	for i in range(n):
		for j in range(i+1,n):
			m = -M[j,i]/M[i,i]
			for k in range(i,n):
				M[j,k] += m*M[i,k]			
	return M

m = np.array([[2,-1,1],[3,3,9],[3,3,5]])
eg(m)

array([[ 2, -1,  1],
       [ 0,  4,  7],
       [ 0,  0, -4]])

## Fatoração LU

In [23]:
import numpy as np

def LU(A):  
    U = np.copy(A)  
    n = np.shape(U)[0]  
    L = np.eye(n)  
    for j in np.arange(n-1):  
        for i in np.arange(j+1,n):  
            L[i,j] = U[i,j]/U[j,j]  
            for k in np.arange(j+1,n):  
                U[i,k] = U[i,k] - L[i,j]*U[j,k]  
            U[i,j] = 0  
    return L, U

m = np.array([[2,-1,1],[3,3,9],[3,3,5]])
print(m)

L,U = LU(m)

print(L)
print(U)

[[ 2 -1  1]
 [ 3  3  9]
 [ 3  3  5]]
[[1.  0.  0. ]
 [1.5 1.  0. ]
 [1.5 1.  1. ]]
[[ 2 -1  1]
 [ 0  4  7]
 [ 0  0 -4]]


## Fatoração de Cholesky

In [19]:
import numpy as np

def cholesky(A):
    L = np.zeros((len(A),len(A)))
    for i, (Ai,Li) in enumerate(zip(A,L)):
        for j, Lj in enumerate(L[:i+1]):
            s = sum(Li[k]*Lj[k] for k in range(j))
            if i==j:
                Li[j] = np.sqrt(Ai[i]-s)
            else:
                Li[j] = (1.0/Lj[j] * (Ai[j]-s))           
    return L

m = np.array([[4,2,-4],[2,10,4],[-4,4,9]])

cholesky(m)

array([[ 2.,  0.,  0.],
       [ 1.,  3.,  0.],
       [-2.,  2.,  1.]])

## Fatoração LDL

In [33]:
import numpy as np

def ldl(A):
    S = np.diag(np.diag(A))
    Sinv = np.diag(1/np.diag(A))
    D = np.matrix(S.dot(S))
    Lch = np.linalg.cholesky(A)
    L = np.matrix(Lch.dot(Sinv))
    return L, D

m = np.array([[4,2,-4],[2,10,4],[-4,4,9]])
ldl(m)


(matrix([[ 0.5       ,  0.        ,  0.        ],
         [ 0.25      ,  0.3       ,  0.        ],
         [-0.5       ,  0.2       ,  0.11111111]]), matrix([[ 16,   0,   0],
         [  0, 100,   0],
         [  0,   0,  81]]))